project:
  type: website
  output-dir: docs

website:
  title: "Welcome!"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cconte363
format:
  html:
    theme: cosmo
    css: styles.css



